### ISSUE TITLE
Example nat-tcp-v4 port_map bug

### ISSUE THREAD

**Issue by YangZhou1997** [williamofockham/NetBricks#102]
Hi, 

Just want to report a bug in https://github.com/williamofockham/NetBricks/blob/809cde67a630d3ada387caedac72d2740f38cab0/examples/nat-tcp-v4/src/main.rs#L115-L121. 

It is a little bit tricky: PORT_MAP.read().unwrap() should be dropped; otherwise, you cannot have mutuable PORT_MAP.write().unwrap() later. 

I have fixed it here: 
https://github.com/YangZhou1997/NetBricks/blob/48c53e2154198423e29dcd0b89003444c959c0c9/examples/nat-tcp-v4/src/main.rs#L119-L133

Best,
Yang

**Comment by zeeshanlakhani** [comment]
👍 will do. Good catch.

**Comment by zeeshanlakhani** [comment]
handled a littler cleaner even in https://github.com/williamofockham/NetBricks/pull/104.
