### ISSUE TITLE
How to run NFs on two cores at the same time. 

### ISSUE THREAD

**Issue by YangZhou1997** [williamofockham/NetBricks#97]
Hi, 

I have run Netbricks on a single core. I notice that the original netbricks paper shows running the same NFs on two cores at the same time. I tried two methods: 

1) set -c 0 -c 1. But only one pipeline is running
2) start another Netbricks on another core with --secondary command line. It shows 
![image](https://user-images.githubusercontent.com/38483906/60529839-72cc6900-9cc5-11e9-8c90-a1297cbf9818.png)
 
Any suggestions and comments are appreciated! 

Best,
Yang

**Comment by zeeshanlakhani** [comment]
@YangZhou1997 good catch. we'll add this back (it got lost as we've updated/refactored the code), nd it should be pretty easy. Will ping you on this thread when we get to it.

**Comment by YangZhou1997** [comment]
@zeeshanlakhani Just wondering how the multi-core feature goes.   
Or, you can explain to me a bit about the scheduler part (I did not understand it well) and I might try to fix it.

**Comment by zeeshanlakhani** [comment]
@YangZhou1997 we’re at atc/hotedge this week, but we’ll fix it. We plan to rewrite the scheduler too, separately, but we’ll get a fix in.

**Comment by zeeshanlakhani** [comment]
@YangZhou1997 I have a small cleanup branch that should allow you to progress. Maybe we can discuss further on gitter: https://gitter.im/williamofockham/NetBricks?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge. 

An example run for two cores:

```shell
./build.sh run macswap -p 0000:00:08.0 -p 0000:00:09.0 -c 0 -c 1 --pool-size=256
Current Cargo Incremental Setting: CARGO_INCREMENTAL=0
Current Rust Backtrace Setting: 1
name: netbricks, secondary: false, pool size: 256, cache size: 32
primary core: 0, cores: [0, 1], strict: false
ports:
	name: 0000:00:08.0, rxq: [0], txq: [0], rxd: 128, txd: 128, loopback: false, tso: false, csumoffload: false
	name: 0000:00:09.0, rxq: [1], txq: [1], rxd: 128, txd: 128, loopback: false, tso: false, csumoffload: false
DPDK args: None
Dope Runtime
Failed to detect # of NUMA nodes from: /sys/devices/system/node/possible. Assuming a single-node system...
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/netbricks/mp_socket
EAL: Probing VFIO support...
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
PMD: pmd port 0 configured successfully
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 1af4:1000 net_virtio
PMD: pmd port 1 configured successfully
Receiving port port: ba:dc:af:eb:ee:f1 (0) rxq: 0 txq: 0
Running 1 pipelines
Receiving port port: ba:dc:af:eb:ee:f2 (1) rxq: 0 txq: 0
Running 1 pipelines
```

Our environment setup makes secondary a bit more difficult (even on pure NB), but maybe we can work that out over chat.

**Comment by zeeshanlakhani** [comment]
Though, we seem to have an issue using multiple cores on the same port. Looking into that now.

**Comment by zeeshanlakhani** [comment]
@YangZhou1997 in attempting to run multiple cores for the same port, you should try to do it via toml config (and not the cli, even as per regular NetBricks), via the rx_queues and tx_queues params. Please give it a try and let us know. We've had some issues w/ multi-core due to our dev env on virtualbox, and we'd like to make sure it works away from vb (as it should).

**Comment by YangZhou1997** [comment]
@zeeshanlakhani Thanks for the info! I will have a try, and post the results here

**Comment by zeeshanlakhani** [comment]
@YangZhou1997 cool. let us know.

**Comment by YangZhou1997** [comment]
Not sure if I understand "via toml config". 

Do you mean setting up two rx_queues (on one port) used by two cores. Just as shown in the following code snippet: 
![image](https://user-images.githubusercontent.com/38483906/61254279-ea70ae00-a731-11e9-960d-9b259dd4d1a4.png)
If so, it seems that I need to change the cli to configure two rx_queues for two cores? What do I need to do with toml config?

**Comment by drunkirishcoder** [comment]
Just realized we actually don't have an example of this in the repo. You can use a file to configure your app in addition to command line args. Here's an example toml file,

```
name = "my-app"
secondary = false
primary_core = 0
cores = [0, 1]
strict = false
pool_size = 512
cache_size = 32

[ports]
  name = "dpdk:eth_af_packet,iface=lo"
  rx_queues = [0, 1]
  tx_queues = [0, 1]
  rxd = 128
  txd = 128
  loopback = false
  tso = false
  csumoffload = false
```

This config should run let you use two cores. And you run it with `./myapp -f myapp.toml`

As @zeeshanlakhani mentioned, we are having trouble testing this because in our VirtualBox environment, we don't have the multiqueue driver support necessary to test running pipelines with multiple cores. Let us know if this works for you.

**Comment by zeeshanlakhani** [comment]
In addition, as @drunkirishcoder alluded to, we should add a config-driven example on this repo as well. 👍

**Comment by YangZhou1997** [comment]
@drunkirishcoder Thanks for the reminder. 
Just a small typo of your example toml file: [ports] should be [[ports]], then everything works perfectly -- I can run Netbricks on two cores with two queues and get nearly double throughput.

Many thanks!

**Comment by zeeshanlakhani** [comment]
great news @YangZhou1997

**Comment by YangZhou1997** [comment]
Specifying multiple queues in config file makes it work
